# Generated by Django 2.0.2 on 2018-02-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('description', models.TextField()),
                ('file', models.URLField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(verbose_name='published date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.Card')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('checkList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.CheckList')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('favorite', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.Table'),
        ),
        migrations.AddField(
            model_name='list',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.Table'),
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoshikiApp.List'),
        ),
    ]
