# Generated by Django 2.0.2 on 2018-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
