# Generated by Django 2.0.2 on 2018-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0002_auto_20180314_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='backgound',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
