# Generated by Django 2.0.2 on 2018-02-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0002_comment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='private',
        ),
    ]
