# Generated by Django 2.0.2 on 2018-03-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0003_table_backgound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='backgound',
            new_name='background',
        ),
    ]
