# Generated by Django 2.0.2 on 2018-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0003_remove_table_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
