# Generated by Django 2.0.2 on 2018-02-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0004_auto_20180223_1455'),
        ('SoshikiApp', '0004_auto_20180222_1610'),
    ]

    operations = [
    ]
