# Generated by Django 2.0.2 on 2018-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0004_auto_20180321_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='background',
            field=models.ImageField(default='background_images/default.png', upload_to='background_images'),
        ),
    ]
