# Generated by Django 2.0.2 on 2018-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0004_auto_20180321_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
