# Generated by Django 2.0.2 on 2018-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0005_auto_20180326_1056'),
        ('SoshikiApp', '0005_auto_20180321_1724'),
    ]

    operations = [
    ]
