# Generated by Django 2.0.2 on 2018-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0006_merge_20180328_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='background',
            field=models.ImageField(default='background_images/default.png', upload_to='background_images'),
        ),
    ]
