# Generated by Django 2.0.2 on 2018-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoshikiApp', '0007_auto_20180403_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='card_files'),
        ),
    ]
